version: "3"

services:

  web:

    image: webpack

    build: .

    command: run prod

    volumes:
      - ./app:/app
      - node_modules:/app/node_modules

    ports:
      - "8079:8079"
      - "8080:8080"

volumes:
  node_modules: