version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.11

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 244157784000.dkr.ecr.us-east-2.amazonaws.com
          aws-access-key-id: AKIATRWHQD7APEUKBYOP
          aws-secret-access-key: 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
          dockerfile: Dockerfile
          region: us-east-2
          repo: arttracks-client
          tag: latest
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: us-east-2
          family: arttracks-client-sv1
          cluster-name: arttracks-client-cls
          container-image-name-updates: container=arttracks-client-sv1,tag=latest


          