/**
 * Created by jarosanger on 8/15/16.
 */
import { createConstants } from './utils';

const constants = createConstants(
    'RESET_USER_AUTH',
    'LOGOUT_USER',
    'SET_USER_AUTH',
    'GET_USER',
    'USER_FAIL',
    'SET_AVATAR',
    'PROFILE_CHECK_REQUEST',
    'PROFILE_CHECK_SUCCESS',

    'START_LOADING',
    'END_LOADING',

    'LOGIN_USER_REQUEST',
    'LOGIN_USER_FAILURE',
    'LOGIN_USER_SUCCESS',

    'SIGNUP_USER_REQUEST',
    'SIGNUP_USER_FAILURE',
    'SIGNUP_USER_SUCCESS',
    'SIGNUP_USER_RESET',

    'FORGOT_PASSWORD_SENT',
    'FORGOT_PASSWORD_REQUEST',
    'FORGOT_PASSWORD_FAILURE',

    'RESET_PASSWORD_REQUEST',
    'RESET_PASSWORD_FAILURE',
    'RESET_PASSWORD_SUCCESS',

    'VERIFY_CODE_REQUEST',
    'VERIFY_CODE_FAILURE',
    'VERIFY_CODE_SUCCESS',

    'CONFIRM_EMAIL_REQUEST',
    'CONFIRM_EMAIL_FAILURE',
    'CONFIRM_EMAIL_SUCCESS',

    'SETTINGS_FAILURE',
    'SETTINGS_GET_REQUEST',
    'SETTINGS_GET_SUCCESS',
    'SETTINGS_SAVE_REQUEST',
    'SETTINGS_SAVE_SUCCESS',

    'BILLING_FAILURE',
    'BILLING_GET_REQUEST',
    'BILLING_GET_SUCCESS',
    'BILLING_SAVE_REQUEST',
    'BILLING_SAVE_SUCCESS',

    'PAYING_FAILURE',
    'PAYING_GET_REQUEST',
    'PAYING_GET_SUCCESS',
    'PAYING_SAVE_REQUEST',
    'PAYING_SAVE_SUCCESS',

    'PROVIDERS_FAILURE',
    'PROVIDERS_GET_REQUEST',
    'PROVIDERS_GET_SUCCESS',
    'PROVIDERS_CONNECT_REQUEST',
    'PROVIDERS_CONNECT_SUCCESS',
    'CONNECTS_ADD_REQUEST',
    'CONNECTS_ADD_SUCCESS',
    'CONNECTS_GET_REQUEST',
    'CONNECTS_GET_SUCCESS',
    'CONNECTS_SAVE_REQUEST',
    'CONNECTS_SAVE_SUCCESS',
    'CONNECTS_DELETE_REQUEST',
    'CONNECTS_DELETE_SUCCESS',

    'VIDEOS_FAILURE',
    'GET_VIDEOS_REQUEST',
    'ALL_VIDEOS',
    'VIDEOS_REMOVE',

    'PROJECT_FAILURE',
    'PROJECT_RESET',
    'PROJECT_SAVE_REQUEST',
    'PROJECT_SAVE_SUCCESS',
    'PROJECT_GET_REQUEST',
    'PROJECT_GET_SUCCESS',
    'PROJECT_DELETE_REQUEST',
    'PROJECT_DELETE_SUCCESS',
    'PROJECT_SET_SUCCESS',
    'PROJECT_SET_THUMBNAIL',

    'ARTWORK_FAILURE',
    'ARTWORK_RESET',
    'ARTWORK_RESET_SETTING',
    'ARTWORK_CREATE_REQUEST',
    'ARTWORK_CREATE_SUCCESS',
    'ARTWORK_DELETE_REQUEST',
    'ARTWORK_DELETE_SUCCESS',
    'ARTWORK_GET_REQUEST',
    'ARTWORK_GET_SUCCESS',
    'ARTWORK_SET_SUCCESS',
    'ARTWORK_UPDATE_REQUEST',
    'ARTWORK_UPDATE_SUCCESS',
    'ARTWORK_TEMPLATE_GET_REQUEST',
    'ARTWORK_TEMPLATE_GET_SUCCESS',

    'TRACKS_FAILURE',
    'TRACKS_RESET',
    'TRACKS_GET_REQUEST',
    'TRACKS_GET_SUCCESS',
    'TRACKS_SAVE_REQUEST',
    'TRACKS_SAVE_SUCCESS',
    'TRACKS_ADD_REQUEST',
    'TRACKS_ADD_SUCCESS',
    'TRACKS_DELETE_REQUEST',
    'TRACKS_DELETE_SUCCESS',
    'TRACKS_UPLOADING_SET',
    'TRACKS_UPLOADING_REMOVE',
    'TRACKS_SCAN_REQUEST',
    'TRACKS_SCAN_SUCCESS',

    'BUILD_FAILURE',
    'BUILD_RESET',
    'BUILD_CHECK_REQUEST',
    'BUILD_CHECK_SUCCESS',
    'BUILD_PROJECT_REQUEST',
    'BUILD_TRACK_REQUEST',
    'BUILD_TRACK_SUCCESS',
    'BUILD_GET_REQUEST',
    'BUILD_GET_SUCCESS',
    'BUILD_TRACK_REMOVE',
    'BUILD_DELETE_REQUEST',
    'BUILD_DELETE_SUCCESS',
    'BUILD_ORDER_REQUEST',
    'BUILD_ORDER_SUCCESS',

    'NOTIFICATIONS_FAILURE',
    'NOTIFICATIONS_GET_REQUEST',
    'NOTIFICATIONS_GET_SUCCESS',
    'NOTIFICATIONS_SAVE_REQUEST',
    'NOTIFICATIONS_SAVE_SUCCESS',
    'NOTIFICATIONS_DELETE_REQUEST',
    'NOTIFICATIONS_DELETE_SUCCESS',

    'RESET_PUBLISH_VIDEO',
    'PUBLISH_VALIDATE_REQUEST',
    'PUBLISH_VALIDATE_ERROR',
    'PUBLISH_VALIDATE_SUCCESS',
    'PUBLISH_VIDEO_REQUEST',
    'PUBLISH_VIDEO_ERROR',
    'PUBLISH_VIDEO_SUCCESS',

    'PLAN_FAILURE',
    'PLAN_GET_REQUEST',
    'PLAN_GET_SUCCESS',
    'QUOTAS_GET_REQUEST',
    'QUOTAS_GET_SUCCESS',
    'PLAN_VIEW_OPTIONS',
    'PLAN_ORDER_REQUEST',
    'PLAN_ORDER_SUCCESS',

    'SHOW_POPUP_PURCHASE',
    'CLOSE_POPUP_PURCHASE',

    'CREDIT_SET_SELECTION',
    'VIDEOTIME_SET_TIMES',
    'VIDEOTIME_SET_TIMES_DISCOUNT_RATE',
    'VIDEOTIME_SET_TIMES_TOTAL_PRICE',

    'PAYMENT_FAILURE',
    'PLAN_UPGRADE_REQUEST',
    'PLAN_UPGRADE_SUCCESS',
    'CUSTOMER_GET_REQUEST',
    'CUSTOMER_GET_SUCCESS',
    'CUSTOMER_CREATE_REQUEST',
    'CUSTOMER_CREATE_SUCCESS',
    'PAYMENT_CREATE_REQUEST',
    'PAYMENT_CREATE_SUCCESS',
    'CARD_CREATE_REQUEST',
    'CARD_CREATE_SUCCESS',
    'CARD_UPDATE_REQUEST',
    'CARD_UPDATE_SUCCESS',
    'CARD_REMOVE_REQUEST',
    'CARD_REMOVE_SUCCESS',
    'INVOICES_GET_REQUEST',
    'INVOICES_GET_SUCCESS',
    'PAYMENTS_GET_REQUEST',
    'PAYMENTS_GET_SUCCESS',
    'PAYMENTS_SET_DETAIL',

    'COUPON_GET_REQUEST',
    'COUPON_GET_ERROR',
    'COUPON_GET_SUCCESS',
);

const configs = {
    SERVER_URL: process.env.SERVER_URL || '//localhost:8080/',
    //SERVER_URL: process.env.SERVER_URL || '//arttracks-client-staging.herokuapp.com/',
    //SERVER_URL: process.env.SERVER_URL || '//beta.arttracks.com/',
    BASE_API_URL: process.env.BASE_API_URL || '//localhost:8000/api/v1/',
    //BASE_API_URL: process.env.BASE_API_URL || '//zerostate.arttracks.com/api/v1/',
    //BASE_API_URL: process.env.BASE_API_URL || '//api.arttracks.com/api/v1/',
    BASE_TAP_URL: process.env.BASE_TAP_URL || 'https://api.tapfiliate.com/1.6/',
    TAP_API_KEY: process.env.BASE_TAP_URL || '64de82909827d670dd2827522f8475be591b9ff3',

    VIDEO_PAGE_LIMIT: process.env.VIDEO_PAGE_LIMIT || 8,

    MAX_VERIFY_COUNT: 6,

    CREDITS: [
        { count: 5, price: 1.00, discount: 0},
        { count: 10, price: 1.00, discount: 0},
        { count: 20, price: 1.00, discount: 0},
        { count: 50, price: 0.94, discount: 5},
        { count: 100, price: 0.90, discount: 10},
        { count: 200, price: 0.85, discount: 15},
    ],
    TIMES_COST_STANDARD: 0.02,
    TIMES_COST_MULTIPLIER: 0.05,
    TIMES_COST_DISCOUNT_FACTOR: 0.85,
    TIMES_COST_LOWEST_DISCOUNT: 0.005,

    AWS_BUCKET: process.env.AWS_BUCKET || "mp3vidi",
    //FILEPICKER_KEY: process.env.FILEPICKER_KEY || "A3wr3EiC8RUKJhe0FwIGfz",
    FILEPICKER_KEY: process.env.FILEPICKER_KEY || "AidoxNXaKRz6t2sExlQdgz",    
    SC_CLIENT_ID: process.env.SC_CLIENT_ID || '976050d0c602302a5c06cbd80a4e1f59',
    SC_CLIENT_SECRET: process.env.SC_CLIENT_SECRET || '4ab65b2f0b5a4660061b35a0a24a7f13',
    SC_REDIRECT_URI: process.env.SC_REDIRECT_URI || 'http://ec2-54-211-100-215.compute-1.amazonaws.com/soundcloud/login',

    FACEBOOK_APPID: process.env.FACEBOOK_APPID || "1350563344977653",
    FACEBOOK_API_SECRET: process.env.FACEBOOK_API_SECRET || '5d78b4850c7896379c9d7d8139866dc6',
    // FACEBOOK_APPID: "304392329723012",
    // FACEBOOK_API_SECRET: '6dd18f57252a9a592fc901e7b5838704',

    TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY || 'w43xofHCr0pQuXgyWiok9Kop2',
    TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET || '7ukQix87AMF285t2ztFerp7jRWuKyL4jjgFq2Xh0nREB4oLZQG',

    YOUTUBE_APP_ID: process.env.YOUTUBE_APP_ID || '338678693531-9156c412a5vjn705thp7v55p6pj8gtt1.apps.googleusercontent.com',
    YOUTUBE_APP_SECRET: process.env.YOUTUBE_APP_SECRET || 'KDVS916OTm4KY4-FonJHF5J-',

    PUSHER_APP_KEY: process.env.PUSHER_APP_KEY || '69a4e70d5e340828aca1',
    PUSHER_ENCRYPTED: false,

    INTERCOM_APP_ID: process.env.INTERCOM_APP_ID || 'zd920cvb',

    STRIPE_LIVE: false,
    STRIPE_PUBLIC_KEY: 'pk_test_Jd3XskH5i8aILdNI8E4YBvwd',
    STRIPE_SECRET_KEY: 'sk_test_S6S9eHFnVvgFV5GSmnA2obDA',
    // STRIPE_PUBLIC_KEY: 'pk_test_82juaf1rPc8ZnbpecXqsC66M',
    // STRIPE_SECRET_KEY: 'sk_test_wHXh0R7elMU6lLaSRtyxISUh',

    AVIARY_CLIENT_KEY: 'f2eb769f94c24691abc2728f64210845',

    CRYPTO_DOWNLOAD_SECRET: 'brenda',
    CRYPTO_DOWNLOAD_ALGO: 'aes-256-ctr',
};

// Set STRIPE keys based on whether we are "LIVE" or not.
if(configs["STRIPE_LIVE"]) {
  configs["STRIPE_PUBLIC_KEY"] = "pk_live_Sydk1HhMCEqhPiiJ26Awa8p1";
  configs["STRIPE_SECRET_KEY"] = "sk_live_8YHSugg8l1lhARC8FrVSvsYB";
}

module.exports = Object.assign({}, constants, configs);
